### PR TITLE
Make `matrix_details::reduce` cache friendly

### PR DESCRIPTION
**Pull request by horror-proton**
- if `begin`...`end` are referring to contiguous memory, I think it's more efficient to access continuous blocks then access interlaced subsets with multiple threads
- `cache[idx] = func( cache[idx], ...;` may result in many threads accessing a small line of memory frequently
- `std::fill( cache.begin(), cache.end(), init );` does not seem right if `init` is not the identity element of `func`, e.g. `recuce(..., 10, std::plus<>{});`
- is `for ( auto id : range( block_begin + 1, block_end ) )` safe? 🤔 

----

benchmark:
```cpp
auto large_matrix feng::rand<int>(2048, 2048);
// ... tic
for (auto i = 0; i < 1000; ++i)
    total += large_matrix.max();
// toc ...
```

### CODE REVIEW

**Comment by fengwang** [comment]
Many thanks for the cache-friendly optimization.

**Comment by horror-proton** [comment]
BTW, I found the document says
```c++
auto one = feng::ones<double>(12, 34);
```
but it does not compile, (`ones<double>(12UL, 34)` does, ) it seems that the compiler has picked up the wrong constructor

```
/usr/include/c++/12.2.0/bits/alloc_traits.h:95:43: error: ‘int’ is not a class, struct, or union type
   95 |       typedef typename _Alloc::value_type value_type;
      |
```

**Comment by fengwang** [comment]
> BTW, I found the document says
> 
> ```c++
> auto one = feng::ones<double>(12, 34);
> ```
> 
> but it does not compile, (`feng::ones<double>(12UL, 34)` does, ) it seems that the compiler has picked up the wrong constructor
> 
> ```
> /usr/include/c++/12.2.0/bits/alloc_traits.h:95:43: error: ‘int’ is not a class, struct, or union type
>    95 |       typedef typename _Alloc::value_type value_type;
>       |
> ```

Which compiler are you using? I develop and test this library currently with __gcc version 12.2.0 __. And I have never test with clang++.

**Comment by fengwang** [comment]
> BTW, I found the document says
> 
> ```c++
> auto one = feng::ones<double>(12, 34);
> ```
> 
> but it does not compile, (`feng::ones<double>(12UL, 34)` does, ) it seems that the compiler has picked up the wrong constructor
> 
> ```
> /usr/include/c++/12.2.0/bits/alloc_traits.h:95:43: error: ‘int’ is not a class, struct, or union type
>    95 |       typedef typename _Alloc::value_type value_type;
>       |
> ```

Should have been fixed by introducing concepts in the most recent commit: https://github.com/fengwang/matrix/commit/6f7f7038b742a1e5609fa00b4fcf90b94e6e7b9f

**Pull request merged**
